### ISSUE TITLE
Proposal - Allow JS config file

### ISSUE THREAD

**Issue by dmastrorillo** [mattferrin/folder-structure-lint#2]
Hi, awesome extension of the original FoldersLint package! 

I am interested in using this internally within my organisation and would like the ability to define some default configs that can be extended and reused 

To enable this, I am proposing the package also accept a JS file (.folder-structure-lint.js) with the config exported as a default export. 

Would you accept a PR facilitating this?

**Comment by mattferrin** [comment]
Yes, that’s definitely something I think should exist. Thank you. I’ll do what I can to help if needed.

**Comment by mattferrin** [comment]
Also @dmastrorillo, please let me know if you or any your peers have additional concerns that should be addressed. Thanks!
